apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseaw-lb-deployment
spec:
  replicas: 1  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx-lb
        image: cithit/roseaw-test2:latest
        ports:
        - containerPort: 80  # Expose NGINX on port 80

---
apiVersion: v1
kind: Service
metadata:
  name: roseaw-lb-service
spec:
  selector:
    app: nginx-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
  type: LoadBalancer
